# Generated by Django 5.2.12 on 2026-03-19 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='email_domain',
            field=models.CharField(default='@example.com', max_length=100),
        ),
    ]
