# Generated by Django 5.2.12 on 2026-03-21 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_eventregistration_qr_code_eventregistration_qr_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='is_attended',
            field=models.BooleanField(default=False),
        ),
    ]
